import Head from 'next/head';
import axios from 'axios';
import { useState } from 'react';

interface Product {
  id: number;
  images: string;
  name: string;
  description: string;
  size: string;
  price:string
}

export async function getStaticProps() {
  const { data } = await axios.get('http://localhost:3002/products/');
  return {
    props: {
      products: data,
    },
  };
}

export default function Home({ products }: { products: Product[] }) {
  const [query, setQuery] = useState('');

  const searchFilter = (array: Product[]) => {
    return array.filter((el) => el.name.toLowerCase().includes(query.toLowerCase()));
  };

  const filtered = searchFilter(products);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setQuery(e.target.value);
  };

  return (
    <div style={{ fontFamily: 'Nunito', backgroundColor: '#f8f9fa', display: 'flex', flexDirection: 'column', alignItems: 'center', minHeight: '100vh' }}>
      <Head>
        <title>search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" />
      </Head>
      <div style={{ marginTop: '40px', textAlign: 'center' }}>
        <h1 style={{ fontSize: '32px', fontWeight: 'bold', marginBottom: '20px' }}>Search for Product</h1>
        <div style={{ width: '400px', margin: '0 auto' }}>
          <input onChange={handleChange} type="text" className="form-control" placeholder="Enter your search query" />
        </div>
      </div>

      <div style={{ width: '90%', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gridGap: '20px', marginTop: '50px' }}>
        {filtered.map((product: Product) => (
          <div key={product.id} style={{ backgroundColor: '#fff', boxShadow: '0px 2px 6px rgba(0, 0, 0, 0.1)', borderRadius: '5px', overflow: 'hidden', padding: '20px' }}>
            <img src={product.images} alt="product card" style={{ width: '100%', height: '200px', objectFit: 'cover', marginBottom: '10px' }} />
            <h2 style={{ fontSize: '18px', fontWeight: 'bold', marginBottom: '10px' }}>{product.name}</h2>
            <p style={{ marginBottom: '5px' }}>
             
            </p>
            <p style={{ marginBottom: '5px' }}>
              <span style={{ fontWeight: 'bold' }}>DESCRIPTION:</span> {product.description}
            </p>
            <p style={{ marginBottom: '5px' }}>
              <span style={{ fontWeight: 'bold' }}>PRICE:</span> {product.price} DNT
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}