export default {
    
    woman :[

        "NEW",
        "BLAZERS",
        "JACKETS | TRENCH COATS",
       " WAISTCOATS | GILETS",
        "DRESSES JUMPSUITS",
        "SHIRTS",
        "T-SHIRTS SWEATSHIRTS",
       " TOPS | BODYSUITS",
        "KNITWEAR",
      "  TROUSERS",
       " JEANS",
       " SKIRTS",
       " SHORTS | SKORTS",
       " SHOES",
       " BAGS",
       " ACCESSORIES | JEWELLERY",
       " BIKINIS | SWIMSUITS",
        "PERFUMES",
        "BEAUTY",
       " CO-ORD SETS",
       " SUITS",
       " SPECIAL PRICES",
        "DRESS TIME",
       " HOLIDAY EDIT",
       " BASICS",
       " SPECIAL EDITION",
        "SEAMLESS NEW",
        "JOIN LIFE",
        "LINEN",
        ],
        man :[

            "EDITION",
            "NEW",
            "ZARA ATHLETICZ",
            "LINEN",
            "CROCHET",
            "BASICS",
            "SUITS",
            "SHIRTS",
            "T-SHIRTS",
            "JACKETS | OVERSHIRTS",
            "TROUSERS",
            "JEANS",
            "SHORTS",
            "HOODIES SWEATSHIRTS",
            "SWEATERS | CARDIGANS",
           " TOTAL LOOK",
            "POLO SHIRTS",
            "SWIMWEAR",
            "CARGO | PARACHUTE",
            "BLAZERS",
           " TRENCH COATS",
            "SHOES",
           " BAGS BACKPACKS",
            "ACCESSORIES",
            "BEAUTY",
            "SPECIAL PRICES",
            "SPECIAL EDITION",
            "JOIN LIFE",
            ],
    kids:[
       " SUMMER CAMP NEW",
        "TRUE NEUTRALS NEW",
        "GIRL | 6-14 YEARS",
        "BOY | 6-14 YEARS",
        "BABY GIRL | 9 MONTHS - 6 YEARS",
        "BABY BOY | 9 MONTHS - 6 YEARS",
        "ACCESSORIES | SHOES",
        "JOIN LIFE",
        ]
}